spring.application.name=sgip-backend

# Configuración de la DB
spring.datasource.url=jdbc:postgresql://localhost:5432/metroDB
spring.datasource.username=postgres
spring.datasource.password=9629

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formato de JSON para UUIDs y Fechas
# spring.jackson.serialization.write-dates-as-timestamps=false

//spring.jpa.hibernate.ddl-auto=update